### ISSUE TITLE
nms 代码有误

### ISSUE THREAD

**Issue by lucienne999** [miaoshuyu/object-detection-usages#1]
https://github.com/miaoshuyu/object-detection-usages/blob/master/src/nms.py#L36
这个应该是Minimum

**Comment by miaoshuyu** [comment]
谢谢指出，已经修改

**Comment by lucienne999** [comment]
https://github.com/miaoshuyu/object-detection-usages/blob/master/src/nms.py#L117
抱歉reopen了, 这一行似乎总会返回第一个框? 因为inds的shape[N, 1] , N=满足阈值的框数目. 这里是不是应该写成
` keep = inds.astype(int).reshape(-1)` , 也可能我们环境的版本(numpy=1.19)有差异, 你可以看一下你的本地环境是否也有这个问题?
